"""
utils/export.py
----------------
Builders for the one-click guidance summary export offered under every chat
answer.

A summary is produced once as plain text (build_summary_text) in a small,
deliberately simple line format:

    CareSync AI - Guidance Summary        <- first non-empty line is the title
    Generated ...

    ## Section heading                    <- "## " prefix marks a heading
    Body paragraph.
      Indented detail line                <- leading spaces mark a detail line
    ---                                   <- horizontal rule

build_summary_pdf() re-renders exactly that text as a paginated A4 PDF with
PyMuPDF, so the two exports can never drift apart in content.
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime
from typing import Any, Dict, List, Sequence

from utils.ui_helpers import STATUS_HINTS, normalize_status, snippet_text

try:  # Recommended modern import, mirroring utils/pdf_processor.py.
    import pymupdf as fitz
except ImportError:  # pragma: no cover - legacy PyMuPDF builds
    try:
        import fitz
    except ImportError:
        fitz = None  # type: ignore[assignment]

# Title line of every export, and the PDF's document-title metadata.
EXPORT_TITLE = "CareSync AI - Guidance Summary"

# Printed at the foot of every export. Field workers act on these summaries
# offline, so the provenance caveat has to travel with the file.
EXPORT_DISCLAIMER = (
    "Generated by CareSync AI from indexed public-health guidance. "
    "This summary is only as current as the cited documents - verify every "
    "action against the source guidance before acting on it."
)

# Longest passage quoted per citation in the export.
_SNIPPET_CHARS = 320

# -- PDF page geometry (A4, in PostScript points) -----------------------------
_PAGE_W, _PAGE_H = 595.0, 842.0
_MARGIN = 56.0
_CONTENT_W = _PAGE_W - (2 * _MARGIN)

_FONT = "helv"
_FONT_BOLD = "hebo"

# Base-14 Helvetica averages a little under half an em per character; used to
# turn a page width into a textwrap character budget.
_CHAR_WIDTH_RATIO = 0.5

_COLOR_BODY = (0.09, 0.13, 0.19)
_COLOR_ACCENT = (0.06, 0.46, 0.43)
_COLOR_MUTED = (0.39, 0.45, 0.55)
_COLOR_RULE = (0.85, 0.89, 0.93)

# PyMuPDF's base-14 fonts encode Latin-1, so typographic characters the LLM
# (or a status hint) may emit are folded down before they reach the page.
_PDF_CHAR_MAP = {
    "—": "-", "–": "-", "‑": "-", "…": "...",
    "→": "->", "←": "<-", "•": "-", "·": "-",
    "’": "'", "‘": "'", "“": '"', "”": '"',
    "⚠️": "!", "⚠": "!", "\U0001f6a8": "!",
    "\U0001f4cc": "*", "✅": "*",
}

# Markdown emphasis the LLM adds for the chat bubble but which reads as noise
# in a printed summary.
_MD_EMPHASIS = re.compile(r"(\*\*|__|\*|`)")
_MD_HEADING = re.compile(r"^\s{0,3}#{1,6}\s+")


def _clean_answer(answer: str) -> str:
    """Strips chat-only markdown so the answer reads cleanly in a flat file."""
    lines: List[str] = []
    for raw in str(answer or "").splitlines():
        line = _MD_HEADING.sub("", raw)
        line = _MD_EMPHASIS.sub("", line)
        lines.append(line.rstrip())
    return "\n".join(lines).strip()


def _citation_lines(sources: Sequence[Dict[str, Any]] | None) -> List[str]:
    """Renders each citation as a numbered block: header, metadata, passage."""
    if not sources:
        return ["No source documents were cited for this answer."]

    lines: List[str] = []
    for position, src in enumerate(sources, start=1):
        status = normalize_status(src.get("status"))
        title = str(src.get("title") or "Untitled Document")

        lines.append(f"{position}. {title}  [{status}]")
        lines.append(
            f"  Version {src.get('version', '-')} - "
            f"Page {src.get('page_number', '-')} - "
            f"Effective {src.get('effective_date', '-')}"
        )
        if status != "ACTIVE":
            lines.append(f"  ! {STATUS_HINTS[status]}")

        passage = " ".join(snippet_text(src).split())
        if passage:
            if len(passage) > _SNIPPET_CHARS:
                passage = passage[:_SNIPPET_CHARS].rsplit(" ", 1)[0] + " ..."
            lines.append(f'  "{passage}"')
        lines.append("")

    return lines


def build_summary_text(
    question: str | None,
    answer: str,
    sources: Sequence[Dict[str, Any]] | None = None,
    conflict_warning: str | None = None,
    filters_summary: str | None = None,
    generated_at: str | datetime | None = None,
) -> str:
    """
    Builds the plain-text guidance summary shared by the TXT and PDF exports.

    Args:
        question:         The field worker's original question.
        answer:           The assistant's answer (chat markdown is stripped).
        sources:          Citation dicts as returned by the RAG pipeline.
        conflict_warning: Conflict summary, when contradicting guidance was found.
        filters_summary:  Human-readable description of the retrieval filters.
        generated_at:     Timestamp of the answer; defaults to now.

    Returns:
        The summary in the line format documented at the top of this module.
    """
    if isinstance(generated_at, datetime):
        stamp = generated_at.strftime("%Y-%m-%d %H:%M")
    elif generated_at:
        stamp = str(generated_at).replace("T", " ")[:16]
    else:
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines: List[str] = [EXPORT_TITLE, f"Generated {stamp}", ""]
    lines += ["## Question", str(question or "-").strip(), ""]

    if filters_summary:
        lines += ["## Retrieval filters", _clean_answer(filters_summary), ""]

    if conflict_warning:
        lines.append("## Conflicting guidance detected")
        for raw in str(conflict_warning).splitlines():
            entry = raw.strip(" •-\t")
            if entry:
                lines.append(f"- {entry}")
        lines.append("")

    lines += ["## Answer", _clean_answer(answer) or "-", ""]

    lines.append(f"## Sources & citations ({len(sources or [])})")
    lines += _citation_lines(sources)

    lines += ["---", EXPORT_DISCLAIMER]
    return "\n".join(lines).rstrip() + "\n"


def summary_filename(question: str | None, extension: str) -> str:
    """
    Builds a descriptive, filesystem-safe download name.

    Example:
        summary_filename("What is the vaccination protocol?", "pdf")
        -> "caresync-summary-what-is-the-vaccination-protocol.pdf"
    """
    slug = re.sub(r"[^a-z0-9]+", "-", str(question or "").lower()).strip("-")
    slug = "-".join([part for part in slug.split("-") if part][:8]) or "answer"
    return f"caresync-summary-{slug}.{extension.lstrip('.')}"


def _pdf_safe(text: str) -> str:
    """Folds a line down to characters PyMuPDF's base-14 fonts can render."""
    for source_char, replacement in _PDF_CHAR_MAP.items():
        text = text.replace(source_char, replacement)
    return text.encode("latin-1", "replace").decode("latin-1")


def pdf_export_available() -> bool:
    """True when PyMuPDF is importable, so the PDF button can be offered."""
    return fitz is not None


def build_summary_pdf(summary_text: str, title: str = EXPORT_TITLE) -> bytes:
    """
    Renders a summary produced by build_summary_text() as a paginated A4 PDF.

    Args:
        summary_text: Output of build_summary_text().
        title:        PDF document-title metadata.

    Returns:
        The PDF file as bytes.

    Raises:
        RuntimeError: If PyMuPDF is not installed (see pdf_export_available()).
    """
    if fitz is None:
        raise RuntimeError("PyMuPDF is not installed - PDF export is unavailable.")

    doc = fitz.open()
    cursor: Dict[str, Any] = {"page": None, "y": _MARGIN}

    def start_page() -> None:
        cursor["page"] = doc.new_page(width=_PAGE_W, height=_PAGE_H)
        cursor["y"] = _MARGIN

    def write(
        text: str,
        size: float = 10.0,
        font: str = _FONT,
        color: tuple = _COLOR_BODY,
        leading: float = 14.0,
        indent: float = 0.0,
    ) -> None:
        budget = max(24, int((_CONTENT_W - indent) / (size * _CHAR_WIDTH_RATIO)))
        for line in textwrap.wrap(_pdf_safe(text), budget) or [""]:
            if cursor["y"] + leading > _PAGE_H - _MARGIN:
                start_page()
            cursor["page"].insert_text(
                (_MARGIN + indent, cursor["y"] + size),
                line,
                fontsize=size,
                fontname=font,
                color=color,
            )
            cursor["y"] += leading

    def rule() -> None:
        if cursor["y"] + 12 > _PAGE_H - _MARGIN:
            start_page()
        cursor["page"].draw_line(
            (_MARGIN, cursor["y"] + 4),
            (_PAGE_W - _MARGIN, cursor["y"] + 4),
            color=_COLOR_RULE,
            width=0.8,
        )
        cursor["y"] += 12

    start_page()
    is_title_line = True

    for raw in str(summary_text).splitlines():
        line = raw.rstrip()

        if not line.strip():
            cursor["y"] += 6
            continue

        if is_title_line:
            write(line, size=16, font=_FONT_BOLD, color=_COLOR_ACCENT, leading=22)
            rule()
            is_title_line = False
        elif line.strip() == "---":
            rule()
        elif line.startswith("## "):
            cursor["y"] += 8
            write(line[3:], size=12, font=_FONT_BOLD, color=_COLOR_ACCENT, leading=18)
        elif line.startswith("  "):
            write(line.strip(), size=8.5, color=_COLOR_MUTED, leading=12, indent=16)
        else:
            write(line)

    # Page numbers, added once the total page count is known.
    total = doc.page_count
    for number, page in enumerate(doc, start=1):
        page.insert_text(
            (_PAGE_W - _MARGIN - 60, _PAGE_H - _MARGIN + 18),
            f"Page {number} of {total}",
            fontsize=8,
            fontname=_FONT,
            color=_COLOR_MUTED,
        )

    doc.set_metadata({"title": _pdf_safe(title), "producer": "CareSync AI"})
    try:
        return doc.tobytes()
    finally:
        doc.close()
